'use client'

import useGasolineGMF from '@app/(apps)/tbm/(globalHooks)/useGasolineGMF'
import useOdometerInputGMF from '@app/(apps)/tbm/(globalHooks)/useOdometerInputGMF'
import useProductMidEditor from '@app/(apps)/tbm/(globalHooks)/useProductMidEditorGMF'
import useCarWashGMF from '@app/(apps)/tbm/(globalHooks)/useCarWashGMF'
import React from 'react'
import {createUpdate} from '@lib/methods/createUpdate'

import useUnchinChildCreator from '@app/(apps)/tbm/(globalHooks)/useUnchinChildCreator'
import useGlobal from '@hooks/globalHooks/useGlobal'
import {doTransaction} from '@lib/server-actions/common-server-actions/doTransaction/doTransaction'

export default function Template({children}) {
  const HK_OdometerInputGMF = useOdometerInputGMF()
  const HK_GasolineGMF = useGasolineGMF()
  const HK_ProductMidEditor = useProductMidEditor()
  const HK_CarWashGMF = useCarWashGMF()
  const HK_UnchinChildCreator = useUnchinChildCreator()

  const {
    query: {g_tbmBaseId},
  } = useGlobal()

  const batch = async () => {
    await seedDriver()
    await seedRouteGroup()
    await seedProduct()
    await seedCar()
    await seedCustomer()
  }

  if (!g_tbmBaseId) {
    return <div>営業所が設定されていません。</div>
  }

  return (
    <div>
      <HK_ProductMidEditor.Modal />
      <HK_GasolineGMF.Modal />

      <HK_OdometerInputGMF.Modal />
      <HK_CarWashGMF.Modal />
      <HK_UnchinChildCreator.Modal />
      {children}
    </div>
  )
}
const seedRouteGroup = async () => {
  const list = [
    {code: 121, name: '中野1-3【N3066】'},
    {code: 122, name: '東松山1【N0269】'},
    {code: 123, name: '荻窪1-12・補十'},
    {code: 124, name: '武蔵府中1-11【N2896】'},
    {code: 125, name: '上福岡2【N0270】'},
    {code: 126, name: '三郷上下6'},
    {code: 127, name: '自由操作便【10Hfree】'},
    {code: 128, name: '自由操作便【国立3-2・二】'},
    {code: 129, name: '小金井ゆパ上下二'},
    {code: 130, name: '土浦・結城　下館2'},
    {code: 131, name: '大宮西8'},
    {code: 132, name: '石神井2-2【N2822】'},
    {code: 133, name: '石神井2-3【N0692】'},
    {code: 134, name: '流山・新岩槻'},
    {code: 135, name: '流山・多摩神奈川1【ﾊﾟﾀｰﾝ②】'},
    {code: 136, name: '流山・神奈川西1【ﾊﾟﾀｰﾝ③】'},
    {code: 137, name: '市川南・印西上下8・日休'},
    {code: 138, name: '新岩槻・羽生　加須2'},
    {code: 139, name: '新岩槻・羽生　加須2'},
    {code: 140, name: '石神井3-1【N0643】'},
    {code: 141, name: '流山・多摩1【ﾊﾟﾀｰﾝ③】'},
    {code: 142, name: '小金井3-1・二-一'},
    {code: 143, name: '板橋3-3【N0628】'},
    {code: 144, name: '土浦・守谷　6'},
    {code: 145, name: '土浦・守谷　休日6'},
    {code: 146, name: '流山・多摩神奈川1【ﾊﾟﾀｰﾝ①】'},
    {code: 147, name: '北部・千葉特設下'},
    {code: 148, name: '東京北部・福岡上二【名古屋神宮中継】'},
    {code: 149, name: '小金井4-2【N2793】'},
    {code: 150, name: '流山・新東京3【ﾊﾟﾀｰﾝ③】'},
    {code: 151, name: '市川南・印西　下11上九・日休'},
    {code: 152, name: '流山・神奈川西【ﾊﾟﾀｰﾝ②】'},
    {code: 153, name: '流山・神奈川西2【ﾊﾟﾀｰﾝ③】'},
    {code: 154, name: '国分寺補4【N0390】'},
    {code: 155, name: '国分寺補4（土）【N0379】'},
    {code: 156, name: '流山・多摩神奈川2【ﾊﾟﾀｰﾝ①】'},
    {code: 157, name: '流山・多摩神奈川2【ﾊﾟﾀｰﾝ②】'},
    {code: 158, name: '流山・多摩神奈川【ﾊﾟﾀｰﾝ③】'},
    {code: 159, name: '東京北部特上二（日曜）'},
    {code: 160, name: '草加上下10【N0306】'},
    {code: 161, name: '神奈川西・水戸上三'},
    {code: 162, name: '調布補5【N0650】'},
    {code: 163, name: '調布補5（土）【N0666】'},
    {code: 164, name: '千葉・名古屋　岐阜上'},
    {code: 165, name: '新岩槻・羽生　加須4'},
    {code: 166, name: '新岩槻・羽生　加須4'},
    {code: 167, name: '川崎東・名古屋神宮下1'},
    {code: 168, name: '姫路上二'},
    {code: 169, name: '千葉・岐阜下'},
    {code: 170, name: '北部・京都下３【N1056】'},
    {code: 171, name: '市川・水戸　下１'},
    {code: 172, name: '神奈川西・千葉下3'},
    {code: 173, name: '東京川越上十一'},
    {code: 174, name: '東京川越上十一（休日）'},
    {code: 175, name: '東京・神奈川西下12'},
    {code: 176, name: '東京・神奈川西土曜下13'},
    {code: 177, name: '豊島(補3・上三-一)'},
    {code: 178, name: '自由操作便【豊島(補3・上三-一)】'},
    {code: 185, name: 'RFC流山・縦持ち(半日)'},
    {code: 186, name: 'RFC流山・縦持ち'},
    {code: 204, name: '臨時便'},
    {code: 205, name: '臨時便'},
    {code: 206, name: '臨時便'},
    {code: 207, name: '臨時便'},
    {code: 208, name: '臨時便'},
    {code: 209, name: '臨時便'},
    {code: 210, name: '臨時便'},
    {code: 211, name: '臨時便'},
    {code: 214, name: '川越・和光N増1'},
    {code: 215, name: '東京北部・中野N増1-1'},
    {code: 216, name: '神奈川西・川越N岩槻増下'},
    {code: 217, name: '神奈川西・千葉N(下3)'},
    {code: 218, name: '自由操作便【小金井N増上三】'},
    {code: 219, name: '岩槻・茨城（楽天SS）R臨下'},
    {code: 220, name: '神奈川西A関東フリー'},
    {code: 221, name: 'N和光年賀増上Ｎ年１'},
    {code: 222, name: 'さいたま新都心・大宮西'},
    {code: 223, name: '流山・神奈川西増1【ﾊﾟﾀｰﾝ④】'},
    {code: 224, name: '流山・神奈川西増2【ﾊﾟﾀｰﾝ④】'},
    {code: 225, name: '流山・市川2【ﾊﾟﾀｰﾝ③】'},
    {code: 226, name: '流山・北部・川越1【ﾊﾟﾀｰﾝ②】'},
    {code: 227, name: '流山・北部・川越2【ﾊﾟﾀｰﾝ②】'},
    {code: 228, name: '東京北部・神奈川西上三'},
    {code: 251, name: '既定便【委託運行】'},
    {code: 252, name: '臨時便【委託運行】'},
    {code: 260, name: '一般'},
    {code: 261, name: '一般'},
    {code: 265, name: '11月分特別付加金'},
    {code: 268, name: '回　　　送'},
    {code: 269, name: '本社応援便'},
    {code: 270, name: '駐車場賃貸代'},
    {code: 271, name: '駐車場賃貸代'},
    {code: 272, name: '駐車場賃貸代'},
    {code: 273, name: '駐車場賃貸代'},
    {code: 274, name: '駐車場賃貸代'},
    {code: 275, name: '駐車場賃貸代'},
    {code: 276, name: '同　　　乗'},
    {code: 277, name: '座　　　学'},
  ]
  const res = await doTransaction({
    transactionQueryList: list
      .filter(item => item.code)
      .map(item => {
        return {
          model: `tbmRouteGroup`,
          method: `upsert`,
          queryObject: {
            where: {unique_tbmBaseId_code: {tbmBaseId: 1, code: String(item.code)}},
            ...createUpdate({...item, code: String(item.code), tbmBaseId: 1}),
          },
        }
      }),
  })

  console.log(res)
}
const seedDriver = async () => {
  const list = [
    {code: 6, name: '加藤　祐司', employeeCode: '14', phone: '080-3468-8467'},
    {code: 8, name: '松本　栄治', employeeCode: '109', phone: '080-3181-4497'},
    {code: 9, name: '高野　一人', employeeCode: '223', phone: '080-4881-7244'},
    {code: 11, name: '鈴木　一則', employeeCode: '159', phone: '080-3181-4490'},
    {code: 14, name: '飯田　崇輔', employeeCode: '501'},
    {code: 15, name: '佐野　淳一', employeeCode: '504', phone: '080-4881-7692'},
    {code: 16, name: '堀江　剛', employeeCode: '508', phone: '080-2779-1943'},
    {code: 17, name: '黒澤　由香', employeeCode: '510'},
    {code: 18, name: '佐藤　秀雄', employeeCode: '511'},
    {code: 19, name: '岡部　公一', employeeCode: '509'},
    {code: 20, name: '笹瀬　正登', employeeCode: '512'},
    {code: 21, name: '桜井　栄也', employeeCode: '513'},
    {code: 22, name: '酒井　栄一', employeeCode: '514'},
    {code: 23, name: '石井　政男', employeeCode: '515'},
    {code: 24, name: '石上　優平', employeeCode: '516'},
    {code: 25, name: '川島　克彦', employeeCode: '517'},
    {code: 26, name: '村上　直人', employeeCode: '518', phone: '080-4881-7862'},
    {code: 27, name: '大和田　茂幸', employeeCode: '519'},
    {code: 28, name: '桜井　仁', employeeCode: '520'},
    {code: 29, name: '坂口　康明', employeeCode: '521'},
    {code: 30, name: '森　由紀江', employeeCode: '522'},
    {code: 31, name: '斧田　愛絵', employeeCode: '523'},
    {code: 32, name: '木原　順一', employeeCode: '524', phone: '080-2779-1438'},
    {code: 33, name: '金澤　孝春', employeeCode: '525'},
    {code: 34, name: '関谷　順子', employeeCode: '526'},
    {code: 35, name: '小尾　貴志', employeeCode: '527'},
    {code: 36, name: '北園　大', employeeCode: '528', phone: '080-4881-7867'},
    {code: 37, name: '加羽沢　洋行', employeeCode: '529'},
    {code: 38, name: '田中　孝義', employeeCode: '530', phone: '070-1270-4213'},
    {code: 39, name: '眞子　靖', employeeCode: '531'},
    {code: 40, name: '小倉　高之', employeeCode: '532'},
    {code: 41, name: '小島　光', employeeCode: '533', phone: '080-3954-8954'},
    {code: 42, name: '櫻井　茂樹', employeeCode: '534'},
    {code: 43, name: '西田　裕幸', employeeCode: '535', phone: '080-3726-2213'},
    {code: 44, name: '柳川　保', employeeCode: '536', phone: '080-3181-4494'},
    {code: 45, name: '中田　俊広', employeeCode: '537', phone: '080-3181-4481'},
    {code: 46, name: '秋場　賢人', employeeCode: '538'},
    {code: 47, name: '斎藤　昭宏', employeeCode: '539', phone: '080-2707-4462'},
    {code: 48, name: '小本　勉', employeeCode: '540', phone: '070-1270-4042'},
    {code: 49, name: '岡本　卓哉', employeeCode: '541', phone: '080-3181-4492'},
    {code: 50, name: '合田　和則', employeeCode: '248'},
    {code: 51, name: '村上　尚哉', employeeCode: '542'},
    {code: 52, name: '須藤　政己', employeeCode: '543', phone: '080-3954-8952'},
    {code: 53, name: '市川　忠', employeeCode: '544'},
    {code: 54, name: '安藤　雅志', employeeCode: '545', phone: '080-4057-2955'},
    {code: 55, name: '中町　敏', employeeCode: '546', phone: '080-4881-7039'},
    {code: 56, name: '鴇田　泰雄', employeeCode: '547'},
    {code: 57, name: '太田　英樹', employeeCode: '548'},
    {code: 58, name: '梅田　義光', employeeCode: '549'},
    {code: 59, name: '増岡　久恵', employeeCode: '550'},
    {code: 60, name: '加藤　隆久', employeeCode: '551'},
    {code: 61, name: '渡邉　智美', employeeCode: '552'},
    {code: 62, name: '本沢　信', employeeCode: '553'},
    {code: 63, name: '川原井　茜音', employeeCode: '554'},
    {code: 64, name: '古澤　恵利', employeeCode: '555'},
    {code: 65, name: '鈴木　達也', employeeCode: '556'},
    {code: 80, name: '愛知営業所', employeeCode: '80'},
    {code: 81, name: '佐藤　憲一', employeeCode: '108'},
    {code: 82, name: '田代　広吉', employeeCode: '200'},
    {code: 85, name: '駐車場賃貸代', employeeCode: '999'},
    {code: 86, name: '関東営業所', employeeCode: '86'},
    {code: 87, name: '社用車', employeeCode: '87'},
    {code: 88, name: '-', employeeCode: '88'},
    {code: 89, name: '委託会社', employeeCode: '89'},
  ].map(item => ({...item, password: item.name, email: item.name}))
  const res = await doTransaction({
    transactionQueryList: list
      .filter(item => item.employeeCode)
      .map(item => {
        return {
          model: `user`,
          method: `upsert`,
          queryObject: {
            where: {employeeCode: item.employeeCode},
            ...createUpdate({...item, password: item.name, code: String(item.code), tbmBaseId: 1, apps: [`tbm`]}),
          },
        }
      }),
  })

  console.log(res)
}
const seedProduct = async () => {
  const list = [
    {code: 1},
    {code: 2},
    {code: 3},
    {code: 4},
    {code: 5, name: '郵便　【既定中型】'},
    {code: 6, name: '郵便　【規定大型】'},
    {code: 7, name: '郵便　【臨時中型】'},
    {code: 8, name: '郵便　【臨時大型】'},
    {code: 9, name: 'JP楽天【既定大型】'},
    {code: 10, name: 'JP楽天【既定中型】'},
    {code: 11, name: ''},
    {code: 12, name: ''},
    {code: 13, name: ''},
    {code: 14, name: ''},
    {code: 15, name: '郵便　【増便中型】'},
    {code: 16, name: '郵便　【増便大型】'},
    {code: 17, name: 'JP楽天【増便大型】'},
    {code: 18, name: '郵便　【年賀大型】'},
    {code: 19, name: '楽天マート'},
    {code: 20, name: 'ケース'},
    {code: 23, name: 'テーブル'},
    {code: 26, name: '駐車場1番'},
    {code: 28, name: '駐車場3番'},
    {code: 29, name: '駐車場4番'},
    {code: 30, name: '駐車場5番'},
    {code: 33, name: '駐車場8番'},
    {code: 34, name: '駐車場9番'},
    {code: 35, name: '-'},
    {code: 36, name: '-'},
  ]
  const res = await doTransaction({
    transactionQueryList: list
      .filter(item => item.name && item.code)
      .map(item => {
        return {
          model: `tbmProduct`,
          method: `upsert`,
          queryObject: {
            where: {name: item.name},
            ...createUpdate({...item, code: String(item.code), tbmBaseId: 1}),
          },
        }
      }),
  })
}
const seedCar = async () => {
  const list = [
    {
      code: 5,
      number: '105',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 6,
      number: '1020',
      vehicleNumber: '久留米130う10-20',
      type: '中型',
      shape: 'ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 7,
      number: '1220',
      vehicleNumber: '久留米130あ12-20',
      type: '中型',
      shape: 'ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 8,
      number: '2020',
      vehicleNumber: '久留米130く20-20',
      type: '中型',
      shape: 'ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 9,
      number: '109',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 10,
      number: '110',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 11,
      number: '2720',
      vehicleNumber: '春日部130あ27-20',
      type: '中型',
      shape: 'ウイング・ゲート（背負）',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥16,391',
    },
    {
      code: 12,
      number: '2820',
      vehicleNumber: '春日部130あ28-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 13,
      number: '3220',
      vehicleNumber: '春日部130あ32-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 14,
      number: '3320',
      vehicleNumber: '春日部130あ33-20',
      type: '中型',
      shape: 'ウイング・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 15,
      number: '115',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 16,
      number: '3420',
      vehicleNumber: '春日部130あ34-20',
      type: '中型',
      shape: 'ウイング・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥16,740',
    },
    {
      code: 17,
      number: '117',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 18,
      number: '118',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 19,
      number: '5320',
      vehicleNumber: '春日部130あ53-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥16,740',
    },
    {
      code: 20,
      number: '5420',
      vehicleNumber: '春日部130あ54-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥16,740',
    },
    {
      code: 21,
      number: '5520',
      vehicleNumber: '春日部130あ55-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥16,740',
    },
    {
      code: 22,
      number: '5720',
      vehicleNumber: '春日部130あ57-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 23,
      number: '123',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 24,
      number: '4994',
      vehicleNumber: '春日部101あ49-94',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥15,923',
    },
    {
      code: 25,
      number: '125',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 26,
      number: '6520',
      vehicleNumber: '春日部130あ65-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥18,233',
    },
    {
      code: 27,
      number: '6420',
      vehicleNumber: '春日部130あ64-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '無',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥18,233',
    },
    {
      code: 28,
      number: '6620',
      vehicleNumber: '久留米130あ66-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥17,419',
    },
    {
      code: 29,
      number: '6920',
      vehicleNumber: '久留米130あ69-20',
      type: '中型',
      shape: 'バン・ゲート（背負）',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥150,000',
      insurance: '¥17,419',
    },
    {
      code: 30,
      number: '8314',
      vehicleNumber: '久留米100あ83-14',
      type: '中型',
      shape: 'バン',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 31,
      number: '131',
      vehicleNumber: '',
      type: '',
      shape: '',
      airSuspension: '',
      oilTireParts: '',
      maintenance: '',
      insurance: '',
    },
    {
      code: 32,
      number: '573',
      vehicleNumber: '春日部100き・5-73',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥15,923',
    },
    {
      code: 33,
      number: '4720',
      vehicleNumber: '春日部130あ47-20',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥17,283',
    },
    {
      code: 34,
      number: '6120',
      vehicleNumber: '春日部130あ61-20',
      type: '大型',
      shape: '１０輪・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥17,786',
    },
    {
      code: 35,
      number: '1593',
      vehicleNumber: '久留米800か15-93',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥13,315',
    },
    {
      code: 36,
      number: '636',
      vehicleNumber: '春日部100き・6-36',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥13,315',
    },
    {
      code: 37,
      number: '3120',
      vehicleNumber: '春日部130あ31-20',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥17,283',
    },
    {
      code: 38,
      number: '9533',
      vehicleNumber: '久留米100か95-33',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥18,029',
    },
    {
      code: 39,
      number: '4220',
      vehicleNumber: '久留米130あ42-20',
      type: '大型',
      shape: '１０輪・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥17,283',
    },
    {
      code: 40,
      number: '4520',
      vehicleNumber: '久留米130あ45-20',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥17,283',
    },
    {
      code: 41,
      number: '2120',
      vehicleNumber: '久留米130あ21-20',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥17,283',
    },
    {
      code: 42,
      number: '7820',
      vehicleNumber: '久留米130あ78-20',
      type: '大型',
      shape: '４軸低床・ウイング',
      airSuspension: '有',
      oilTireParts: '¥30,000',
      maintenance: '¥250,000',
      insurance: '¥17,283',
    },
  ]
  const res = await doTransaction({
    transactionQueryList: list
      .filter(item => item.vehicleNumber)
      .map(item => {
        const {number, ...data} = item
        data[`vehicleNumber`] = number

        return {
          model: `tbmVehicle`,
          method: `upsert`,
          queryObject: {
            where: {vehicleNumber: data.vehicleNumber},
            ...createUpdate({...data, code: String(data.code), tbmBaseId: 1}),
          },
        }
      }),
  })
}
const seedCustomer = async () => {
  const tbmCustomers = [
    '愛知営業所',
    '（株）大野商事',
    '㈱京浜ライン',
    '関東営業所',
    '株式会社　ギオンデリバリーサービス',
    '株式会社　ギオンデリバリーサービス　松戸センター',
    '常南通運　株式会社',
    '東海輸送　株式会社',
    '田主丸営業所',
    '日本郵便輸送　東海支社',
    '日本郵便輸送　名古屋（営）',
    '日本郵便輸送　四日市(営)',
    '日本郵便輸送　岐阜(営)',
    '日本郵便輸送　浜松(営)',
    '日本郵便輸送　静岡(営)',
    '日本郵便輸送　豊橋(営)',
    '日本郵便輸送　南関東支社',
    '日本郵便輸送　東京支社',
    '日本郵便輸送　新東京(営)',
    '日本郵便輸送　東京北(営)',
    '日本郵便輸送　近畿支社',
    '日本郵便輸送　九州支社',
    '日本郵便輸送　関東支社',
    '（株）ナワショウ',
    '(有)丸和運輸',
    'ミフネトランスポート㈱',
    'レビック',
    '和束運輸㈱',
    '(有)和束企画',
    '株式会社　和香商事',
  ]
  const res = await doTransaction({
    transactionQueryList: tbmCustomers.map(item => {
      return {
        model: `tbmCustomer`,
        method: `upsert`,
        queryObject: {
          where: {
            unique_tbmBaseId_name: {tbmBaseId: 1, name: item},
          },
          ...createUpdate({
            tbmBaseId: 1,
            name: item,
          }),
        },
      }
    }),
  })
}
